---
- hosts: HOSTMACHINE
  remote_user: USERMACHINE
  tasks:
    - name: Mise de la liste des packets
      shell: apt update

    - name: Upgrade de la version SSH server
      shell: DEBIAN_FRONTEND=noninteractive apt-get -yq install openssh-server