---
- name: "Requete dans une base"
  hosts: testdb
  remote_user: root
  
  tasks:
    - name: "Sauvegarde de la base de données"
      modulesave:
        db_name: aistest
        request: backup
    
    - name: "Installation de SSHPass"
      apt:
        name:
          - sshpass
          
    
    - name: "Envoie de la back up vers la machine Ansible"
      command: sshpass -p toto scp /root/backup.sql  root@192.168.145.130:/home/abdelansible/library
