---
- name: "Requete dans une base"
  hosts: HOSTMACHINE
  remote_user: USER
  
  tasks:
    - name: "Sauvegarde de la base de données"
      modulesave:
        db_name: DBNAME
        request: backup
    
    - name: "Installation de SSHPass"
      apt:
        name:
          - sshpass
          
    
    - name: "Envoie de la back up vers la machine Ansible"
      command: sshpass -p MDP scp /USER/backup.sql  USER@IP OU HOST:/home/USER/library
