---
- name: "Requete dans une base"
  hosts: HOSTMACHINE
  remote_user: USER
  
  tasks:
    - name: "Installation de SSHPass"
      apt:
        name:
          - sshpass
          
    
    - name: "Envoie de la backup vers la machine cible"
      command: sshpass -p MDP scp USER@IP/HOST:/home/USER/library/backup.sql /USER/

    
    - name: "Restauration de la base de donnée"
      modulesave:
        db_name: BDNAME
        request: restore