---
- hosts: DBCLI
  remote_user: root
  tasks:
    - name: Téléchargement du script d'installation de docker
      shell: 
        wget -O dockerinstall.sh https://get.docker.com
    
    - name: Modification des droits sur le script
      shell:
        chmod 777 ./dockerinstall.sh
    
    - name: Lancement du script d'installation docker
      shell:
        bash ./dockerinstall.sh
    
    - name: Ajout de l'utilisateur au groupe docker
      shell:
        usermod -aG docker root
    
    - name: Redémarrage du service docker
      shell:
        systemctl restart docker

    - name: Supression du script d'installation docker
      shell:
        rm -R ./dockerinstall.sh

    - name: Pull de l'image docker guacamole/guacd
      shell:
        docker pull guacamole/guacd

    - name: Pull de l'image docker guacamole/guacamole
      shell:
        docker pull guacamole/guacd

    - name: Pull de l'image mysql/mysql avec lancement de configuration
      shell:
        docker run --name guacamoledb -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=guacdb -d mysql/mysql-server
    
    - name: Création du dossier de stockage de la BDD
      shell:
        mkdir -p /opt/guacamole/mysql

    - name: Génération du script d'initialisation
      shell:
        docker run --rm guacamole/guacamole /opt/guacamole/bin/initdb.sh --mysql > /opt/guacamole/mysql/01-initdb.sql
    
    - name: Copie du script d'initialisation de la BDD dans le docker MYSQL
      shell:
        docker cp /opt/guacamole/mysql/01-initdb.sql guacamoledb:/docker-entrypoint-initdb.d
    
    - name: Téléchargement du script mysql.sh
      shell: wget https://github.com/Kabelouze/Project-IT/raw/main/Scripts%20Linux/mysql.sh

    - name: Copie du script mysql.sh vers le docker
      shell:
        docker cp mysql.sh guacamoledb:/docker-entrypoint-initdb.d

    - name: Commande Bash dans le conteneur guacamoledb (lancement du script d'initialisation de la BDD)
      community.docker.docker_container_exec:
        container: guacamoledb
        command: /bin/bash -c "mysql -u root --password=password -D guacdb < /docker-entrypoint-initdb.d/01-initdb.sql"

    - name: Commande Bash lancement du script mysql.sh
      community.docker.docker_container_exec:
        container: guacamoledb
        command: /bin/bash -c "bash /docker-entrypoint-initdb.d/mysql.sh"

    - name: Lancement du serveur docker guacamole
      shell:
        docker run --name guacamole-server -d guacamole/guacd

    - name: Lancement du client guacamole
      shell:
        docker run --name guacamole-client --link guacamole-server:guacd --link guacamoledb:mysql -e MYSQL_DATABASE=guacdb -e MYSQL_USER=guacadmin -e MYSQL_PASSWORD=password -d -p 80:8080 guacamole/guacamole